### ISSUE TITLE
Whats the hardware used for?

### ISSUE THREAD

**Issue by xism4** [Ennar1991/ZydDash#1]
Im interested on trying that and i want same hardware youre using for that

**Comment by Ennar1991** [comment]
The example code provided and shown in the picture is running on an ESP32 development module and a SH1106 compatible OLED display, though adaptation to other means of displaying is very easy. Almost all ESP32 modules should work.

I will incorporate this information into the readme.

**Comment by xism4** [comment]
> The example code provided and shown in the picture is running on an ESP32 development module and a SH1106 compatible OLED display, though adaptation to other means of displaying is very easy. Almost all ESP32 modules should work.
> 
> I will incorporate this information into the readme.

Thanks, other question can this software set máximum speed on KM. 

We tried to unlimit the New scotters but sadly the controller cant be opened.

**Comment by xism4** [comment]
> > The example code provided and shown in the picture is running on an ESP32 development module and a SH1106 compatible OLED display, though adaptation to other means of displaying is very easy. Almost all ESP32 modules should work.
> > I will incorporate this information into the readme.
> 
> Thanks, other question can this software set máximum speed on KM.
> 
> We tried to unlimit the New scotters but sadly the controller cant be opened.

If you have any idea contact me from Gmail we can do buisness
Soportexism4@gmail.com
